### ISSUE TITLE
User setup

### ISSUE THREAD

**Issue by worxli** [vochabular/admin-frontend#23]
When a user logs in the dashboard for the first time, he/she should go through a small setup wizard. The user should put in its name and its language (DE/EN) and if the translator role has been set on auth0, the user should put his translation languages.

**Comment by YanickSchraner** [comment]
Maybe also define a display name / user name which we can use to indicate the author of comments. 
Would we store this also in django?

**Comment by dafrie** [comment]
hm, OTH this property (nickname) is also set already in Auth0? We need to define a "strategy" now, where we set/configure user related info. Maybe we nonetheless manage users in Django and on user creation, create a new user via the Auth0 management API in Auth0?

**Comment by YanickSchraner** [comment]
But then we have no control over who can sign up for our application, or we would have to implement something like e-mail invitations? Lets here @worxli opinion on that.
In my opinion, we would still have a user object on our Django backend and a DB entry.

**Comment by dafrie** [comment]
I know, from #22 I agree we anyway need a user obj. in django. Especially since we want to display names who commented etc, then we don't have a way around. 

My thought was about how is the process when we add a new user. But actually I think now I remember how we wanted to about it:

- An admin creates the user in auth0 just with the email address and a default password.
- The user then can change his pasword, sign up to the Vocha-Dashboard
- The SPA will issue a request to retrieve the user information.
- Django authenticates the user with the supplied JWT. As it can not find the user, it will create a new user.
- Since the user settings in Django are empty, it will redirect the user to the wizard screen.
- The user sets his settings, these will be stored as user_settings somewhere in Django

**Comment by worxli** [comment]
Yes.

**Comment by worxli** [comment]
`/auth` has a `userUpdate`migration.
